name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v2.1.0
        with:
          runtime: node@24
          cache: true
          require-lockfile: true
      - run: pnpm test
